version: '3'
services:
  docker-tut:
    container_name: docker-tut
    image: docker-tut
    ports:
      - "8090:8090"
    environment:
      - dbUri=mongodb://docker-tut-mongo/docker-tut
    links:
      - docker-tut-mongo 
    build: .
  docker-tut-mongo:
    container_name: docker-tut-mongo
    image: mongo
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: